---

env: local
listen:
  bind_ip: 127.0.0.1
  port: 9800
  key: api-key
sql:
  enabled: false
  driver: mysqli
  hostname: localhost
  username: username
  password: password
  database: db
  port: 8080
  prefix: prefix_
telegram:
  enabled: false
  api_key: telegram-api-key
