name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare configuration file
        run: |
          sed -i 's|${LOG_ENV}|'"$LOG_ENV"'|g' ocapi-config.yml
          sed -i 's|${LISTEN_PORT}|'"$LISTEN_PORT"'|g' ocapi-config.yml
          sed -i 's|${API_KEY}|'"$API_KEY"'|g' ocapi-config.yml
          sed -i 's|${SQL_DRIVER}|'"$SQL_DRIVER"'|g' ocapi-config.yml
          sed -i 's|${SQL_HOSTNAME}|'"$SQL_HOSTNAME"'|g' ocapi-config.yml
          sed -i 's|${SQL_USERNAME}|'"$SQL_USERNAME"'|g' ocapi-config.yml
          sed -i 's|${SQL_PASSWORD}|'"$SQL_PASSWORD"'|g' ocapi-config.yml
          sed -i 's|${SQL_DATABASE}|'"$SQL_DATABASE"'|g' ocapi-config.yml
          sed -i 's|${SQL_PORT}|'"$SQL_PORT"'|g' ocapi-config.yml
          sed -i 's|${SQL_PREFIX}|'"$SQL_PREFIX"'|g' ocapi-config.yml
          sed -i 's|${TELEGRAM_API_KEY}|'"$TELEGRAM_API_KEY"'|g' ocapi-config.yml
        env:
          LOG_ENV: ${{ vars.LOG_ENV }}
          LISTEN_PORT: ${{ vars.LISTEN_PORT }}
          API_KEY: ${{ secrets.API_KEY }}
          SQL_DRIVER: ${{ vars.SQL_DRIVER }}
          SQL_HOSTNAME: ${{ vars.SQL_HOSTNAME }}
          SQL_USERNAME: ${{ vars.SQL_USERNAME }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_DATABASE: ${{ vars.SQL_DATABASE }}
          SQL_PORT: ${{ vars.SQL_PORT }}
          SQL_PREFIX: ${{ vars.SQL_PREFIX }}
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}

      - name: Copy Configuration to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "ocapi-config.yml"
          target: "/etc/conf"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go application
        run: |
          go build -v -o ocapi ./cmd/opencart

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "ocapi"
          target: "/usr/local/bin/"

      - name: Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            systemctl restart ocapi.service 
